### ISSUE TITLE
Cannot allocate memory & threads

### ISSUE THREAD

**Issue by gorkemyontem** [gorkemyontem/SWE-573-2020#31]
In some cases, analyser fails to run with the following error message:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 302, in _handle_workers
    pool._maintain_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 206, in _maintain_pool
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 199, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 120, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by gorkemyontem** [comment]
Must be a multithread or a db issue

**Comment by gorkemyontem** [comment]
Getting this error:
```
'CategorizedTaggedCorpusReader' object has no attribute '_LazyCorpusLoader__args'
``` 
Looks related should I create a new issue?
